### ISSUE TITLE
Использование конкатенации вместе с f-строками

### ISSUE THREAD

**Issue by MarshalX** [jellythefish/isd-hse-cs-project#1]
https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L20
https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L25

Предлагаю использовать что-то одно.

**Comment by jellythefish** [comment]
https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L20
Отвечает за то, чтобы возвратить уже сконвертированный текстовый файл в ответ на POST-запрос к серверу.
https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L25
Это путь к  текстовому файлу, который загружает пользователь.
То есть это два разных файла.
Немного не понял проблемы, уточните?

**Comment by MarshalX** [comment]
> https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L20
> 
> Отвечает за то, чтобы возвратить уже сконвертированный текстовый файл в ответ на POST-запрос к серверу.
> 
> https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L25
> 
> Это путь к текстовому файлу, который загружает пользователь.
> То есть это два разных файла.
> Немного не понял проблемы, уточните?

Давайте я просто покажу как это должно было бы выглядеть при использовании только f-строк.

```python
file_path =  f'{root_directory}\\target-files\{file_name}' 
```

**Comment by jellythefish** [comment]
> > https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L20
> > 
> > Отвечает за то, чтобы возвратить уже сконвертированный текстовый файл в ответ на POST-запрос к серверу.
> > https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/run-server.py#L25
> > 
> > Это путь к текстовому файлу, который загружает пользователь.
> > То есть это два разных файла.
> > Немного не понял проблемы, уточните?
> 
> Давайте я просто покажу как это должно было бы выглядеть при использовании только f-строк.
> 
> ```python
> file_path =  f'{root_directory}\\target-files\{file_name}' 
> ```

Понял, что это касается code style, да, спасибо. Исправил

**Comment by jellythefish** [comment]
> Давайте я просто покажу как это должно было бы выглядеть при использовании только f-строк.
> 
> ```python
> file_path =  f'{root_directory}\\target-files\{file_name}' 
> ```
Понял, что это касается code style, да, спасибо. Исправил
