### ISSUE TITLE
requirements.txt вместо virtualenv

### ISSUE THREAD

**Issue by MarshalX** [jellythefish/isd-hse-cs-project#2]
https://github.com/jellythefish/isd-hse-cs-project/blob/d85289137d218b8736ebbce0f50e22cf1fc9023c/virtualenv/pyvenv.cfg#L1

Дело в том, что виртуальное окружение привязано к вашей системе и сетапить его надо на каждой машине не путем передачи папки. Куда лучше указать список зависимостей, например как тут: https://github.com/LoDThe/DocumentConverter (тоже не самый лучший пример, ибо указаны зависимости зависимостей).

Из этого следует, что сетап гайд не корректен

**Comment by jellythefish** [comment]
> Куда лучше указать список зависимостей, например как тут: https://github.com/LoDThe/DocumentConverter (тоже не самый лучший пример, ибо указаны зависимости зависимостей).

Fixed.

**Comment by MarshalX** [comment]
> > Куда лучше указать список зависимостей, например как тут: https://github.com/LoDThe/DocumentConverter (тоже не самый лучший пример, ибо указаны зависимости зависимостей).
> 
> Fixed.

Замечательно. Если есть желание исправлять дальше, то могу еще замечаний накидать.

**Comment by jellythefish** [comment]
> Замечательно. Если есть желание исправлять дальше, то могу еще замечаний накидать

Да, буду рад любому ревью!
