### ISSUE TITLE
Сборка под Linux

### ISSUE THREAD

**Issue by lodthe** [jellythefish/isd-hse-cs-project#3]
Некорректно работает на Linux из-за '\' в путях к директориям + запуск .exe.
Сервер не возвращает ошибку, если кодировка является недопустимой или не была распознана.
Так же, рассмотрите вариант использования python-magic и встроенной python конвертации текстов.

**Comment by jellythefish** [comment]
- [x] Исправил реализацию путей в скриптах с помощью pathlib. Теперь нет проблемы различия стиля путей Windows/Unix. 
- [x] Сделал кросплатформенным запуск iconv на Windows через .exe и на Unix-системах через iconv.
- [x] Добавил обработку ошибок, если распознанная кодировка или целевая кодировка вдруг недопустима/не поддерживается при конвертации через утилиту iconv. Ошибка с кодом 400 возвращается непосредственно в ответ на запрос через curl.

- Обработку ошибок разпознавания начальной кодировки текстового файла не делаю, поскольку утилита chardet так или иначе вернет какую-то кодировку для файла, поэтому целесообразно отталкиваться уже от того, а поддерживает ли эту кодировку iconv.
